name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Rust environment
        run: |
          rustup install nightly
          rustup +nightly component add rust-src
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run wasm
          npm run build
      - name: Lint
        run: |
          npm run lint
          npx prettier --check src/**/*.{ts,vue}
